import { mkdirSync, writeFileSync } from "fs";
import { dirname, resolve } from "path";
import { glob } from "glob";
import { Validator } from "./Validator";
import type { NanoObject, StoreEntry, RouteEntry, PrismaEntry } from "../types/objects";
import type { FindOptions } from "../types/loader";
import { FileReader } from "./FileReader";

export abstract class FileLoader {

  /**
   * 1. Validates a `.prisma` file.
   * 2. Loads a generated Prisma client module (`client.ts`, or `client.js`)
   */
  public static async findPrismaClient(clientPath: string, schemaPath: string): Promise<PrismaEntry> {
    // Reads the schema
    const content = FileReader.loadFile(schemaPath).replace(/\/\/.*$/gm, "");

    // Validates it
    if (!Validator.validateUnique(content, "prisma", schemaPath)) {
      throw new Error(`[nano-app] [ERROR] ${schemaPath} is not a valid Prisma schema.`);
    }

    // Loads the client
    try {
      return (await FileReader.loadModule<{ PrismaClient: PrismaEntry }>(clientPath))?.PrismaClient;
    } catch (error: any) {
      throw new Error(`[nano-app] [ERROR] The Prisma client ${clientPath} could not be loaded: ${error?.message ?? error}`);
    }
  }



  /** Finds `*.<extension>.ts` (or built `.js`) files and returns `{ [subPath]: defaultExport }` */
  public static async findMany<T extends RouteEntry | StoreEntry>({ extension, savePath, sourceDir, save = false }: FindOptions): Promise<NanoObject<T>> {
    // Resolves the paths
    const srcDir = (sourceDir || `src/${extension}s`).replace(/^\.\//, "").replace(/\/$/, "");
    const filePaths = await glob(`${srcDir}/**/*.${extension}.{ts,js}`, { posix: true, ignore: "**/*.d.ts" });

    // Builds the entries object
    const entries: NanoObject<T> = {};

    for (const filePath of filePaths) {
      const fileSubPath = filePath
        .slice(srcDir.length)
        .replace(new RegExp(`\\.${extension}\\.(ts|js)$`), "");
      entries[fileSubPath] = await FileReader.loadModule<T>(filePath, { default: true });
    }

    // Drops invalid entries (one invalid file does not discard the rest)
    const valid = Validator.validate<T>(entries, extension);

    // Persists the entries object when requested. Used savePath or default path.
    if (save) {
      this.save<T>(valid, savePath || resolve(process.cwd(), "node_modules", "@nano-app", "data", `${extension}s.cjs`));
    }

    // Always returns the entries object
    return valid;
  }


  /** Writes a `{ [filePath]: fileDefaultExport }` map to the given path. */
  private static save<T extends RouteEntry | StoreEntry>(data: NanoObject<T>, outPath: string): void {
    const SERIALIZE = (value: unknown, indent = 0): string => {
      const pad = "  ".repeat(indent);
      const padInner = "  ".repeat(indent + 1);

      if (value === null) return "null";
      if (value === undefined) return "undefined";
      if (typeof value === "function") return value.toString();
      if (typeof value === "string") return JSON.stringify(value);
      if (typeof value === "number" || typeof value === "boolean") return String(value);

      if (Array.isArray(value)) {
        if (value.length === 0) return "[]";
        const items = value
          .map((v) => `${padInner}${SERIALIZE(v, indent + 1)}`)
          .join(",\n");
        return `[\n${items}\n${pad}]`;
      }

      if (typeof value === "object") {
        const entries = Object.entries(value as Record<string, unknown>);
        if (entries.length === 0) return "{}";
        const lines = entries
          .map(([k, v]) => `${padInner}${JSON.stringify(k)}: ${SERIALIZE(v, indent + 1)}`)
          .join(",\n");
        return `{\n${lines}\n${pad}}`;
      }

      return String(value);
    }

    const GENERATE_EXPORT = (content: string) => `${'// Auto-generated by @nano-app.\n' +
      '// Do not edit manually.\n' +
      '"use strict";\n' +
      'module.exports = {\n' + content + '\n};'
      }`;

    // Builds the file contents
    const output = GENERATE_EXPORT(
      Object.entries(data)
        .map(([filePath, value]) => `  ${JSON.stringify(filePath)}: ${SERIALIZE(value, 1)}`)
        .join(",\n")
    );

    // Creates the destination directory if missing and writes the file
    mkdirSync(dirname(outPath), { recursive: true });
    writeFileSync(outPath, output, "utf-8");

    console.log(`[nano-app] File generated: ${outPath}`);
  }
}
