import { existsSync } from "fs";
import { FileLoader, FileReader, NanoObject } from "@nano-app/core";
import type { DatabaseConfig } from "../types/database";
import type { PrismaPg } from "@prisma/adapter-pg";
import { getDir } from "../../const";

export abstract class Database {
  private static adapter?: PrismaPg;

  /** Mounted clients, by name */
  private static clients: NanoObject = {};

  /** Initializes the Database client */
  static async init(): Promise<void> {
    // Checks the DATABASE_URL is defined
    const url = process.env.DATABASE_URL;
    if (!url) {
      throw new Error("[nano-app] [ERROR] The DATABASE_URL environment variable is not defined.");
    }
  
    // Create the adapter (imported only when needed)
    const { PrismaPg } = await import("@prisma/adapter-pg");
    this.adapter = new PrismaPg({ connectionString: url });
  }

  /** Gets a client by name */
  static get(name: string): any {
    return this.clients[name];
  }

  /** Mounts a generated Prisma client */
  static async mount(name: string, { schemaPath }: DatabaseConfig): Promise<any> {
    // Fail if trying to mount a client that already exists
    if (this.get(name)) {
      throw new Error(`[nano-app] [ERROR] The database "${name}" is already mounted.`);
    }

    // Every client is generated by nano-app, named as its plugin
    const clientPath = `${process.cwd()}/.nano-app/prisma-clients/${name}/generated/client.ts`;
    if (!existsSync(clientPath)) {
      throw new Error(`[nano-app] [ERROR] The prisma client of "${name}" does not exist. Run \`npx nano-app generate ${name}\`.`);
    }

    // Creates the adapter when no consumer database did
    if (!this.adapter) await this.init();

    // Loads the client and validates the schema
    const PrismaClient = await FileLoader.findPrismaClient(clientPath, schemaPath);

    // Plugins' schemas (in the framework's plugins/) use only nano_*; the consumer's never do
    const isPlugin = schemaPath.startsWith(getDir("plugins"));
    const declared = FileReader.loadFile(schemaPath).replace(/\/\/.*$/gm, "").match(/datasource\s+\w+\s*\{[^}]*schemas\s*=\s*\[([^\]]*)\]/s)?.[1] ?? "";
    const schemas = [...declared.matchAll(/["']([^"']+)["']/g)].map(([, schema]) => schema);
    if (isPlugin ? !schemas.length || schemas.some(schema => !schema.startsWith("nano_")) : schemas.some(schema => schema.startsWith("nano_"))) {
      throw new Error(`[nano-app] [ERROR] ${schemaPath}: ${isPlugin ? "a plugin declares only nano_* schemas" : "the nano_* schemas are reserved for plugins"}.`);
    }

    let client;
    try {
      // Instantiates it with the pg adapter
      client = new PrismaClient({ adapter: this.adapter });
    } catch (error: any) {
      throw new Error(`[nano-app] [ERROR] Cannot instantiate the database "${name}" from ${clientPath}: ${error?.message ?? error}`);
    }

    // A plugin's tables are pushed in development: checks each model can be read
    if (isPlugin) {
      for (const [, model] of FileReader.loadFile(schemaPath).matchAll(/^\s*model\s+(\w+)/gm)) {
        await client[model[0].toLowerCase() + model.slice(1)].findFirst().catch((error: any) => {
          throw new Error(`[nano-app] [ERROR] The database "${name}" is not ready: ${String(error?.message ?? error).trim().split("\n").pop()} Run \`npx nano-app push ${name}\`.`);
        });
      }
    }

    // Mounts the client
    this.clients[name] = client;
    console.log(`[nano-app] [INFO] Database "${name}" mounted`);

    return client;
  }
}
